version: "3.9"
services:
  server:
    restart: always
    build: .
    ports:
      - 8000:8000
    environment:
      YT_API_KEY: ${YT_API_KEY}
      MONGODB_URI: ${DOCKER_MONGODB_URI}
    depends_on:
      - database

  database:
    image: mongo
    restart: always
    ports:
      - 27017:27017
